sonar.projectKey=TomPi-2_Mercadona_Prevee
sonar.organization=tompi-2

# Nombre y versión del proyecto
sonar.projectName=Mercadona_Prevee
sonar.projectVersion=1.0

# Rutas de código fuente (Dart/Flutter)
sonar.sources=lib
sonar.tests=test

# Archivos a excluir
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.config.dart,**/generated/**,**/*.pb.dart
sonar.test.exclusions=test/**

# Codificación del código fuente
sonar.sourceEncoding=UTF-8

# Lenguaje principal
sonar.language=dart

# Reportes de cobertura (si los generas)
# sonar.dart.coverage.reportPaths=coverage/lcov.info